version: '3'

networks:
  dev:
    driver: bridge
services:
  db:
    image: postgres:latest
    container_name: financialmanager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dev
